name       : ois
version    : 1.3
release    : 2
source     :
    - http://vorboss.dl.sourceforge.net/project/wgois/Source%20Release/1.3/ois_v1-3.tar.gz : 50fa76d827e119a80e2c86a5196ac4354e556f80b0a4fa440f69e1057b37faa1
license    : Zlib
component  : programming.library
summary    : Object Oriented Input System (OIS) is meant to be a cross platform, simple
    solution for using all kinds of Input Devices
description: |
    Object Oriented Input System (OIS) is meant to be a cross platform, simple solution for using all kinds of Input Devices
libsplit   : no
builddeps  :
    - pkgconfig(sdl2)
    - pkgconfig(xaw7)
    - pkgconfig(x11)
setup      : |
    %patch -p1 < $pkgfiles/gcc47.patch
    sh bootstrap
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
patterns   :
    - devel :
        - /usr/lib64/libOIS.so
